version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: la_bibliotheque
      MYSQL_USER: fredlib
      MYSQL_PASSWORD: $${ $MYSQL_PASSWORD }
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456

volumes:
  db_data:
